[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wealthwise-ai"
version = "0.1.0"
description = "AI-Powered Personal Finance Advisor"
authors = [
    { name = "Anuj Dev Singh" }
]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
